/// <reference types="typescript" />

// declare function require(name: string)
// var sampleModule = require("modulename")

declare module "calculateTotalSum"
declare module "capitalize"
declare module "convertDate"
declare module "convertDateShort"
declare module "convertPrice"
declare module "convertToEmail"
declare module "convertToPascal"
declare module "convertYoutube"
declare module "detectLanguage"
declare module "getFirstName"
declare module "getLastName"
declare module "getPercentage"
declare module "getRandom"
declare module "getRandomAvatar"
declare module "getRandomDate"
declare module "getRandomNumber"
declare module "getRandomString"
declare module "getRandomTime"
declare module "getTimeNow"
declare module "getToday"
declare module "passwordRegex"
declare module "emailRegex"
declare module "scrollToTop"
declare module "slugify"
declare module "stringifyPx"
declare module "unslugify"
